CREATE TABLE IF NOT EXISTS users (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    email    VARCHAR(60)  NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role_id  INTEGER NOT NULL,
    status   VARCHAR(20) NOT NULL DEFAULT 'active',
    created  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
