CREATE TABLE IF NOT EXISTS diners (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL,
    phone      VARCHAR(15),
    user_id    INTEGER NOT NULL UNIQUE,
    created    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);
