CREATE TABLE IF NOT EXISTS carts (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    diner_id INTEGER NOT NULL,
    store_id INTEGER NOT NULL,
    created  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (diner_id, store_id),
    FOREIGN KEY (diner_id) REFERENCES diners(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (store_id) REFERENCES stores(id) ON UPDATE CASCADE ON DELETE CASCADE
);
