CREATE TABLE IF NOT EXISTS order_reviews (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    store_rating INTEGER NOT NULL CHECK (store_rating BETWEEN 1 AND 5),
    comment      TEXT,
    created      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_id     INTEGER NOT NULL UNIQUE,
    diner_id     INTEGER NOT NULL,
    store_id     INTEGER NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (diner_id) REFERENCES diners(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (store_id) REFERENCES stores(id) ON UPDATE CASCADE ON DELETE CASCADE
);
